# CMake generated Testfile for 
# Source directory: /home/itsp/semin/ccs22/libsnark
# Build directory: /home/itsp/semin/ccs22/libsnark
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(common_routing_algorithms_test "/home/itsp/semin/ccs22/libsnark/common_routing_algorithms_test")
set_tests_properties(common_routing_algorithms_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;856;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib1_simple_test "/home/itsp/semin/ccs22/libsnark/gadgetlib1_simple_test")
set_tests_properties(gadgetlib1_simple_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;860;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib1_r1cs_ppzksnark_verifier_gadget_test "/home/itsp/semin/ccs22/libsnark/gadgetlib1_r1cs_ppzksnark_verifier_gadget_test")
set_tests_properties(gadgetlib1_r1cs_ppzksnark_verifier_gadget_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;864;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_adapters_test "/home/itsp/semin/ccs22/libsnark/gadgetlib2_adapters_test")
set_tests_properties(gadgetlib2_adapters_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;868;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_constraint_test "/home/itsp/semin/ccs22/libsnark/gadgetlib2_constraint_test")
set_tests_properties(gadgetlib2_constraint_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;872;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_gadget_test "/home/itsp/semin/ccs22/libsnark/gadgetlib2_gadget_test")
set_tests_properties(gadgetlib2_gadget_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;876;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_integration_test "/home/itsp/semin/ccs22/libsnark/gadgetlib2_integration_test")
set_tests_properties(gadgetlib2_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;880;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_protoboard_test "/home/itsp/semin/ccs22/libsnark/gadgetlib2_protoboard_test")
set_tests_properties(gadgetlib2_protoboard_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;884;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_variable_test "/home/itsp/semin/ccs22/libsnark/gadgetlib2_variable_test")
set_tests_properties(gadgetlib2_variable_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;888;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(relations_qap_test "/home/itsp/semin/ccs22/libsnark/relations_qap_test")
set_tests_properties(relations_qap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;892;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(relations_sap_test "/home/itsp/semin/ccs22/libsnark/relations_sap_test")
set_tests_properties(relations_sap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;896;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(relations_ssp_test "/home/itsp/semin/ccs22/libsnark/relations_ssp_test")
set_tests_properties(relations_ssp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;900;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_bacs_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_bacs_ppzksnark_test")
set_tests_properties(zk_proof_systems_bacs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;904;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_r1cs_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;908;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_se_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_r1cs_se_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_se_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;912;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_gg_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_r1cs_gg_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_gg_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;916;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_ram_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_ram_ppzksnark_test")
set_tests_properties(zk_proof_systems_ram_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;920;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_tbcs_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_tbcs_ppzksnark_test")
set_tests_properties(zk_proof_systems_tbcs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;924;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_uscs_ppzksnark_test "/home/itsp/semin/ccs22/libsnark/zk_proof_systems_uscs_ppzksnark_test")
set_tests_properties(zk_proof_systems_uscs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;928;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(test_knapsack_gadget "/home/itsp/semin/ccs22/libsnark/test_knapsack_gadget")
set_tests_properties(test_knapsack_gadget PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;932;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(test_merkle_tree_gadgets "/home/itsp/semin/ccs22/libsnark/test_merkle_tree_gadgets")
set_tests_properties(test_merkle_tree_gadgets PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;936;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(test_set_commitment_gadget "/home/itsp/semin/ccs22/libsnark/test_set_commitment_gadget")
set_tests_properties(test_set_commitment_gadget PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;940;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
add_test(test_sha256_gadget "/home/itsp/semin/ccs22/libsnark/test_sha256_gadget")
set_tests_properties(test_sha256_gadget PROPERTIES  _BACKTRACE_TRIPLES "/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;944;add_test;/home/itsp/semin/ccs22/libsnark/CMakeLists.txt;0;")
